theme: jekyll-theme-minimal
title: Office of Medicaid Innovation
description: The Office of Medicaid Innovation (OMI) is a specialty unit within the University of Illinois System. Established in 2012 via an Intergovernmental Agreement with the Illinois Department of Healthcare and Family Services (HFS), OMI's mission is to provide administrative, clinical, and operational services to HFS in support of its administration of Illinois' Medicaid Program.
